import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-primary-fixed": "#001849",
        "on-secondary": "#00363a",
        "surface-variant": "#353436",
        "on-error": "#690005",
        "on-error-container": "#ffdad6",
        "surface-container-lowest": "#0e0e0f",
        "on-primary-container": "#f8f7ff",
        "tertiary-fixed-dim": "#00e55b",
        "tertiary-container": "#008431",
        "tertiary": "#00e55b",
        "surface-container": "#201f20",
        "surface-container-highest": "#353436",
        "inverse-on-surface": "#313031",
        "background": "#131314",
        "tertiary-fixed": "#6bff83",
        "on-tertiary-fixed": "#002107",
        "on-surface-variant": "#c2c6d8",
        "surface": "#131314",
        "on-background": "#e5e2e3",
        "on-secondary-fixed": "#002022",
        "on-surface": "#e5e2e3",
        "secondary-fixed": "#7df4ff",
        "inverse-surface": "#e5e2e3",
        "surface-container-low": "#1c1b1c",
        "outline": "#8c90a1",
        "inverse-primary": "#0054d6",
        "outline-variant": "#424656",
        "surface-bright": "#3a393a",
        "primary-container": "#0066ff",
        "primary-fixed-dim": "#b3c5ff",
        "error-container": "#93000a",
        "on-secondary-container": "#00686f",
        "on-tertiary-container": "#e6ffe1",
        "on-tertiary": "#003911",
        "surface-tint": "#b3c5ff",
        "primary-fixed": "#dae1ff",
        "secondary": "#d3fbff",
        "secondary-fixed-dim": "#00dbe9",
        "primary": "#b3c5ff",
        "on-tertiary-fixed-variant": "#00531b",
        "error": "#ffb4ab",
        "surface-dim": "#131314",
        "secondary-container": "#00eefc",
        "on-primary-fixed-variant": "#003fa4",
        "surface-container-high": "#2a2a2b",
        "on-secondary-fixed-variant": "#004f54",
        "on-primary": "#002b75",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "space-lg": "1.5rem",
        "space-2xl": "3rem",
        gutter: "1rem",
        "space-md": "1rem",
        "space-sm": "0.5rem",
        "margin-desktop": "3rem",
        "space-3xl": "4rem",
        "margin-tablet": "2rem",
        "margin-mobile": "1rem",
        "space-xl": "2rem",
        "space-2xs": "0.125rem",
        "space-xs": "0.25rem",
      },
      fontFamily: {
        "headline-lg-mobile": ["Space Grotesk", "Geist", "sans-serif"],
        "display-xl": ["Space Grotesk", "Geist", "sans-serif"],
        "body-lg": ["JetBrains Mono", "monospace"],
        "code-inline": ["JetBrains Mono", "monospace"],
        "headline-sm": ["Space Grotesk", "Geist", "sans-serif"],
        "display-xl-mobile": ["Space Grotesk", "Geist", "sans-serif"],
        "label-caps": ["JetBrains Mono", "monospace"],
        "headline-lg": ["Space Grotesk", "Geist", "sans-serif"],
        "body-sm": ["JetBrains Mono", "monospace"],
        "headline-md": ["Space Grotesk", "Geist", "sans-serif"],
        "body-md": ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "headline-lg-mobile": ["28px", { lineHeight: "34px", letterSpacing: "-0.02em", fontWeight: "500" }],
        "display-xl": ["72px", { lineHeight: "76px", letterSpacing: "-0.04em", fontWeight: "600" }],
        "body-lg": ["15px", { lineHeight: "24px", letterSpacing: "-0.01em", fontWeight: "400" }],
        "code-inline": ["12px", { lineHeight: "16px", letterSpacing: "0.03em", fontWeight: "500" }],
        "headline-sm": ["18px", { lineHeight: "26px", letterSpacing: "-0.01em", fontWeight: "500" }],
        "display-xl-mobile": ["40px", { lineHeight: "44px", letterSpacing: "-0.03em", fontWeight: "600" }],
        "label-caps": ["10px", { lineHeight: "12px", letterSpacing: "0.08em", fontWeight: "500" }],
        "headline-lg": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "500" }],
        "body-sm": ["11px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.015em", fontWeight: "500" }],
        "body-md": ["13px", { lineHeight: "20px", letterSpacing: "0em", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};

export default config;
